# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tts.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ttts.proto\x12\x03tts\"5\n\x10SynthesisRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x13\n\x0bsample_rate\x18\x02 \x01(\x05\"?\n\rAudioResponse\x12\x0b\n\x03wav\x18\x01 \x01(\x0c\x12\x13\n\x0bsample_rate\x18\x02 \x01(\x05\x12\x0c\n\x04note\x18\x03 \x01(\t2>\n\x03TTS\x12\x37\n\nSynthesize\x12\x15.tts.SynthesisRequest\x1a\x12.tts.AudioResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tts_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SYNTHESISREQUEST']._serialized_start=18
  _globals['_SYNTHESISREQUEST']._serialized_end=71
  _globals['_AUDIORESPONSE']._serialized_start=73
  _globals['_AUDIORESPONSE']._serialized_end=136
  _globals['_TTS']._serialized_start=138
  _globals['_TTS']._serialized_end=200
# @@protoc_insertion_point(module_scope)
