# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import tts_pb2 as tts__pb2


class TTSStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Synthesize = channel.stream_stream(
                '/tts.TTS/Synthesize',
                request_serializer=tts__pb2.SynthesisRequest.SerializeToString,
                response_deserializer=tts__pb2.AudioChunk.FromString,
                )


class TTSServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Synthesize(self, request_iterator, context):
        """client sends one request (or a few), server streams audio frames back
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TTSServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Synthesize': grpc.stream_stream_rpc_method_handler(
                    servicer.Synthesize,
                    request_deserializer=tts__pb2.SynthesisRequest.FromString,
                    response_serializer=tts__pb2.AudioChunk.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tts.TTS', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TTS(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Synthesize(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/tts.TTS/Synthesize',
            tts__pb2.SynthesisRequest.SerializeToString,
            tts__pb2.AudioChunk.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
